config/routes.rb
EcoTrends::Application.routes.draw do

  get "comparison" => 'datastores#compare', as: :comparison
  get "testcharts" => 'search#test'
  resources :datastores
  get 'account' => 'accounts#index'
  put 'account/:id' => 'accounts#update'
  get 'login' => 'login#show'
  get 'reset_password' => 'login#edit'
  get 'reset/:token' => "registration#edit"
  put 'reset/:token' => "registration#update"
  post 'login' => 'login#create'
  put 'reset' => 'login#update'
  get 'logout' => 'login#destroy'
  get 'signup' => 'registration#show'
  post 'signup' => 'registration#create'

  get "splash/index"

  get "home/index"

  get "home/about"

  get "home/publications"

  get "home/synthesis"

  get "home/contact"

  get "home/glossary"

  get "home/infographics"

  get "home/datastore"

  get "home/search"

  get "home/test"

  get "home/comparison"

  get "home/dataset"

  get "home/graph"

  get "home/dataset2"

  get "policies" => "home#policies"

  get "participating-sites" => "home#participating"

  post 'contact' => 'contact_us#create'

  get 'contact' =>  'contact_us#new'

  resources :search

  get "metadata" => "search#metadata"
  get "derived-data/:id" => "search#data"

  root :to => 'splash#index'

end

app/controllers/datastores_controller.rb
class DatastoresController < ApplicationController
  def index
    @datastores = SavedDataset.where(iduser: current_user_id) #.includes(:extracat_metadata)
  end


  def compare
    if params[:docids].nil?
      flash[:error] = "Please select one or more datasets to compare."
      redirect_to "/datastores"
      return
    end

    @data = setup_dataset(params)
    @data_length = 0
    @data[:datasets].each do |data_set|
      if data_set[:data].count > @data_length
        @data_length = data_set[:data].count
      end
    end
    @show_lines = params[:shooby].blank? ? true : false
    @show_plots = params[:shonby].blank? ? true : false
    if params[:both_off].present?
      if (@show_plots.present? && @show_lines.present?) && (params[:both_off] == "true")
        @show_lines = false
        @show_plots = false
      elsif (@show_plots.blank? && @show_lines.blank?) && params[:both_off] == "false"
        @show_lines = true
        @show_plots = true
      end
    end
    #binding.pry
  end

  def create
    is_not = "not "
    if params[:docids].present? && current_user.present?
      docids_array = if params[:docids].is_a?(String)
                       [params[:docids]]
                     else
                       params[:docids]
                     end
      docids_array.each do |doc|
        existing = SavedDataset.where(iduser: current_user_id, docid: doc)
        if existing.blank?
          s = SavedDataset.new
          s.iduser = current_user_id
          s.docid = doc #see if this works
          is_not = "" if s.save
        end
      end
      set_datastore_array
    else
      is_not = ""
    end
    respond_to do |format|
      format.html {redirect_to datastores_path, notice: "Dataset #{is_not}was saved"}
      format.json { render json: {success: true}.to_json, status: 200}
    end

  end

  def destroy
    is_not = "not "
    @saved_dataset = SavedDataset.where(idsave: params[:id])
    if @saved_dataset.present?
      @saved_dataset.first.destroy
      is_not = ""
    end

    set_datastore_array
    redirect_to datastores_path, notice: "Dataset was #{is_not}deleted"
  end
  # 1. based on the docid from the site, we have to know the label range of the # of years from all comparable graphs.
  # 2. based on the label range, we can search for the 'year' it is available and print obs in the data array or nil
  # 3. continue for all of them in the docids array from the site.
  def setup_dataset(params)
    #labels need a min and max the year array and then to print out each one in the range...maybe?
    @dataset_array, @labels = ExtracatMetadata.get_values_by_docid(params[:docids])
    {      labels: @labels,      datasets: set_dataset_array(@labels)   }
  end
  #probably don't need map but just going with flow.
  def set_dataset_array(labels)
    arr = []
    @dataset_array.each_with_index do |data_set, index|
      arr << prettify_data_set(data_set, index, labels)
    end
    arr
  end

  def prettify_data_set(data_set, index = 0, labels)
    colour = pick_colour(index)
    {
      label: data_set[:record].variable_name,
      fillColor: "rgba(#{colour},0.2)",
      strokeColor: "rgba(#{colour},1)",
      pointColor: "rgba(#{colour},1)",
      pointStrokeColor: "#fff",
      pointHighlightFill: "#fff",
      pointHighlightStroke: "rgba(#{colour},1)",
      data: clean_up_data(data_set, labels),
      legendTemplate:"<ul class=\"<%%=name.toLowerCase()%>-legend\"><%% for (var i=0; i<segments.length; i++){%><li><div class=\"legend-item-color\" style=\"background-color:<%%=segments[i].fillColor%>\"></div><%%if(segments[i].label){%><%%=segments[i].label%><%%}%></li><%%}%></ul>",

    }
  end

  def clean_up_data(data_set, labels)
    labels.map do |year|
      data_set[:datum].has_key?(year.to_s) ? data_set[:datum][year.to_s] : nil
    end
  end

  def pick_colour(index)
    # binding.pry
    # colour1 = index % 3 ? colour_value(index) : 0
    # colour2 = index % 2 ? colour_value(index) : 0
    # colour3 = index % 5 ? colour_value(index) : 0
    # "#{colour1},#{colour2},#{colour3}"
    case index
    when 0
      "255, 0, 0"
    when 1
      "0, 255, 0"
    when 2
      "0, 0, 255"
    else
      "#{100 - index}, #{index}, #{index + 150}"
    end

  end


  # def colour_value(index)
  #   puts index
  #   (255 - index)/(index == 0 ? 1 : index)
  # end
end

app/helpers/datastore_helper.rb
module DatastoreHelper
end

app/views/datastores/compare.html.erb
<h1>Comparing Datasets</h1>
<p><%= link_to "Back", search_index_path %> | <%= link_to "Print / Save PDF", "#", { id: "print-link"}   %>
  <i id="print-info" class="fa fa-info-circle fa-1" aria-hidden="true" title="If you would like to download a PDF please select 'Save as PDF' from your print preview window"></i>
  <%= form_tag(comparison_path(params), method: :get, id: "formmy") do %><%= hidden_field_tag :docids, params["docids"] %> <%= hidden_field_tag :both_off %>Customize Chart: <input type="checkbox" name="shooby" id="shooby" value="show_plots" class="chart-checkbox" <%= "checked" if @show_plots.present?%>> Plot Points <input type="checkbox" name="shonby" id="shonby" class="chart-checkbox" value="show_lines" <%= "checked" if @show_lines.present?%>> Grid Lines | <%= link_to "Reset Both", comparison_path(docids: params[:docids]) %><% end %></p>
<% chart_width = (@data_length / 20) * 450 %>
<% if chart_width < 900 %>
    <% chart_width = 900 %>
<% end %>
<% options = {width: chart_width, generateLegend: true, scaleShowGridLines: @show_lines.present?, pointDot: @show_plots.present?, bezierCurve:false} %>
<%= line_chart @data, options %>

app/views/datastores/index.html.erb
<div class="row">
  <div class="span12 hover">
    <h1>Data Store</h1>
    <h5>Your Saved Datasets</h5>
  </div> <!-- span -->
</div> <!-- row -->
<div class="row">


  <%= form_tag('/comparison', method: :get) do %>
    <div class="span12 headerbar">
      <% if @datastores.count > 0 %>
        <button class="btn">Compare Selected</button>
      <% else %>
          <button class="btn" disabled>Compare Selected</button>
      <% end %>
    </div> <!-- span -->
</div> <!-- row -->

<!-- BEGIN SEARCH RESULTS -->
  <% @datastores.each_with_index do |result, index| %>
  <div class="row">
    <div class="span12">
      <div class="row">
	<div class="span1">
	  <fieldset>
	      <%= check_box_tag :docid, result.docid.to_s, false, {multiple: true, name: 'docids[]'} %>&nbsp;&nbsp;
	  </fieldset>
	</div> <!-- span -->
	<div class="span9">
	  <h4 class="darkbrown"><%= link_to result.extracat_metadata.variable_name, search_path(result.extracat_metadata.entryid) %></h4>
	  <p class="searchbody"><%= result.docid%></p>
	  <p><%= image_tag "station.png", class: "icon" %><%= result.extracat_metadata.station_names %></b>/ <%= result.extracat_metadata.site_name%></a>
	    --<%= result.extracat_metadata.topic %> / <%= result.extracat_metadata.subtopic %> -- <%= result.extracat_metadata.unit_name%> -- <%= result.extracat_metadata.timescale %></p>
	</div> <!-- span -->
	<div class="span2 searchright">
	  <h4><%= result.extracat_metadata.begin_date.year%> - <%= result.extracat_metadata.end_date.year %></h4>
	  <%= link_to image_tag("chart.png"), search_path(result.extracat_metadata.entryid) %><hr/>
	  <p><i class="fa fa-delete"></i><%= link_to image_tag("remove.png"), datastore_path(result.idsave), method: :delete, data: { confirm: 'Are you sure?' } %></p>
	</div> <!-- span -->
      </div> <!-- row -->
    </div> <!-- span -->
  </div>
    <% if index <= @datastores.count - 2 %>
      <hr/>
    <% end %>
  <% end %>
  <% end %> <!-- form end one hopes -->

<% if @datastores.nil? || @datastores.count < 1 %>
      <h2>It doesn't look like you have any datasets to compare. Please go to the <%= link_to "search", "/search"%>
        section of the website in order to find datasets you can add to your datastore to compare.
      </h2>
      <h3>Adding datasets to your datastore</h3>
      <p>Click on the <%= link_to "search option", "/search" %> in your menu. Once you search and find an item you are looking for you can click to see more details about that data. You will be presented with a chart and and other info about the data you have found and there will be a button that allows you to add the result to your datastore. </p>
      <%= image_tag "add-to-datastore.png", class:'add-to-datastore'%>

      <h3>Powerful Charting</h3>
      <a href="#charting"></a>
      <p>Once you have added some items to your datastore you can select them from your datastore list and compair them side by side. </p>
      <%= image_tag "compairing-datasets.png", class:'compairing-datasets'%>
<% end %>