config/routes.rb
EcoTrends::Application.routes.draw do

  get "comparison" => 'datastores#compare', as: :comparison
  get "testcharts" => 'search#test'
  resources :datastores
  get 'account' => 'accounts#index'
  put 'account/:id' => 'accounts#update'
  get 'login' => 'login#show'
  get 'reset_password' => 'login#edit'
  get 'reset/:token' => "registration#edit"
  put 'reset/:token' => "registration#update"
  post 'login' => 'login#create'
  put 'reset' => 'login#update'
  get 'logout' => 'login#destroy'
  get 'signup' => 'registration#show'
  post 'signup' => 'registration#create'

  get "splash/index"

  get "home/index"

  get "home/about"

  get "home/publications"

  get "home/synthesis"

  get "home/contact"

  get "home/glossary"

  get "home/infographics"

  get "home/datastore"

  get "home/search"

  get "home/test"

  get "home/comparison"

  get "home/dataset"

  get "home/graph"

  get "home/dataset2"

  get "policies" => "home#policies"

  get "participating-sites" => "home#participating"

  post 'contact' => 'contact_us#create'

  get 'contact' =>  'contact_us#new'

  resources :search

  get "metadata" => "search#metadata"
  get "derived-data/:id" => "search#data"

  root :to => 'splash#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :allow_only_signed_in
  layout "search", :only => :search
  layout "graph", :only => :graph
  require 'json'

  def index
  end

  def about
    @message = ContactUs.new

  end
  def graph

  end
  def glossary
    @terms = [{"Abundance" => "The number of individuals or the representation of the number of individuals of a species in a particular ecosystem. Unit: number of individuals/sampling area or sampling effort."},
{"Biogeochemistry" => "The biogeochemistry of ecosystems involves the movement or cycling of elements (e.g., sulfur, carbon, nitrogen) and compounds (e.g., water) through the biotic (e.g., plants, animals, microbes) and abiotic (e.g., soils, atmosphere) components of an ecosystem."},
{"Biomass" => "The mass per unit area of living material (plants, animals, microbes). Unit: g/m2 or kg/ha."},
{"Cover" => "The amount or proportion of surface area occupied by plants or animals. Unit: %."},
{"Decomposition" => "The breakdown of organic matter (e.g., litter) accompanied by the release of carbon dioxide and other inorganic compounds. It is a key process in nutrient cycling."},
{"Density" => "The number of individuals found in an area. Unit: #/m2 or #/ha."},
{"Fire disturbance" => "Area burned by a fire. Unit: ha, or % of area."},
{"Human population density" => "Number of people per unit area."},
{"Human population size" => "Number of people living in a specified geographic area at a specified time."},
{"Ice duration" => "The number of days in a year when a water body (e.g., lake, a part of an ocean) is covered by ice. Unit: days/year."},
{"Land use" => "Land use is the human modification of natural environment or wilderness into built environment such as farmland, pastures, and settlements."},
{"Litter" => "Recently fallen plant material that is only partially decomposed. Unit: %."},
{"Net primary production" => "The amount of carbon or energy (usually measured as biomass) fixed by primary producers (e.g., plants, algae) minus their respiratory loss. It can be used for growth and reproduction of primary producers, and is available for consumption by herbivores. Unit: g/m2/yr."},
{"Palmer drought severity index" => "Developed by Wayne Palmer in the 1960s and uses temperature and rainfall information in a formula to determine dryness. It uses a 0 as normal, and drought is shown in terms of minus numbers; for example, minus 2 is moderate drought, minus 3 is severe drought, and minus 4 is extreme drought."},
{"Plant phenology" => "The timing of life history events, such as initiation of growth, flowering and dormancy."},
{"Precipitation" => "The amount and pattern of rainfall and snowfall. Unit: cm"},
{"Precipitation chemistry" => "Concentration or total amount of an element (e.g., nitrogen, sulfur, calcium, chloride, phosphate) in precipitation. It can be expressed as volume-weighted concentration or deposition. Volume-weighted concentration is concentration per unit volume of precipitation (mg/L). It is measured on a subsample of precipitation and then converted to total volume of precipitation collected. Deposition is total amount of an element per unit of land area (kg/ha). It is converted from volume-weighted concentration based on the area receiving precipitation."},
{"Primary production" => "The amount of carbon or energy (usually measured as biomass) transformed from CO2 to organic carbon by primary producers (e.g., plants, algae) per unit area in a specified time period, usually seasonally or annually. Unit: g/m2/yr. Unit: cm"},
{"Sea level" => "Annual mean sea level is defined as the annual arithmetic means of hourly heights relative to the National Tidal Datum Epoch (i.e., the most recent mean sea level datum established by CO-OPS currently the mean sea level 1983-2001). Unit: m."},
{"Secchi disk" => "A circular disk created in 1865 by Pietro Angelo Secchi. It is used to measure water transparency in oceans and lakes. The disc is mounted on a pole or line, and lowered slowly down in the water. The depth at which the pattern on the disk is no longer visible is taken as a measure of the transparency of the water."},
{"Soil moisture" => "The total amount of water, including the water vapor, in an unsaturated soil. Unit: % by volume."},
{"Soil radiation" => "The visible and near visible (ultra violet and near infrared) radiation emitted from the sun received per unit area. Unit: MJ/m2 The temperature of soil at a specified depth. Unit: oC"},
{"Species diversity" => "Species diversity is a measure of the diversity within an ecological community that incorporates both species richness and the evenness of species' abundances."},
{"Species richness" => "The number of species in a community. Unit: number of species/sampling area or sampling effort."},
{"Storm disturbance" => "Number of major storms or hurricanes per year."},
{"Stream flow" => "Measured as stream discharge here, which is the volume of water moving down a stream or river per unit of time. Unit: L/s"},
{"Surface water chemistry" => "Concentration of an element (e.g., nitrogen, sulfur, calcium, chloride, phosphate) per unit volume of water in surface water (e.g., stream, lake, coastal water). Unit: mg/L."},
{"Water table" => "The underground depth at which point the ground is totally saturated with water. Unit: m."},
{"Water temperature" => "Unit: oC"},
{"Water turbidity" => "A measure of the degree to which the water looses its transparency due to the presence of suspended particulates. It is commonly measured by using a Secchi disk. Unit: m."},
{"Wind speed" => "Unit: m/s"}]
  end

  def infographics
    puts Rails.root
    @file = File.read("#{Rails.root}/public/images/infographics/infographics.json")
    @json_hash = JSON.parse(@file)
    @imagePath = ""
    # puts "here is the JSON :"
    #
    # @json_hash["images"].each do |key|
    #
    #   puts "key: #{key['image']['name']}"
    #
    # end
  end

  def datastore
  end

  def search
  end

  def tester
  end

  def comparison
  end

  def dataset
  end

  def dataset2
  end

  def policies

  end

  def participating

  end

  def contact
    @message = ContactUs.new
  end

  def publications

  end

  def synthesis

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="row">
	<div class="span12">
		<h1>About EcoTrends</h1>
	  <p>
      It is widely recognized that the Earth's environment is changing in many aspects at local, regional, and global scales. Dramatic changes have occurred in climate, land cover, and habitat availability with important consequences for plant, animal, and human populations. Long-term data are needed to assess the rate and direction of change, to distinguish directional trends in these changes (e.g., persistent increases or decreases) from short-term variability (e.g., multi-year cycles), and to forecast environmental conditions in the future.
      <b>The EcoTrends Project is designed to promote and enable the use and synthesis of long-term data to examine these trends in the Earth's ecosystems.</b>
    </p>
    <p>
      Data relevant to these trends have been collected for decades to centuries from over 100 experimental forests, rangeland research stations, and other ecological research sites that can be used to examine these long-term trends. This large suite of sites represents a wide range of ecosystem types, from forests to grasslands and shrublands, freshwater lakes and streams, near coastal marine and estuaries as well as urban areas and systems in the arctic and Antarctica.
      These data can be used to address many different kinds of questions: for example, what are trends in climate, disturbances, and land use? and how do these trends influence ecological responses through time? Examples of the use of these long-term data to address critical science questions can be found in our accompanying book, "Our Changing World: Insights from Long-Term Ecological Research". The "raw" datasets and their associated metadata (descriptions of the data) are available from internet home pages of individual sites or investigators. However, these detailed datasets are often of most use to scientists familiar with the site, ecosystem, and method of data collection. In many cases, it is very difficult for someone unfamiliar with the data to access and use the raw data to address new and interesting questions. The site-based format also makes it difficult for scientists to use the raw data to address more synthetic questions that require long-term data from many sites or from different types of ecosystems or from different time periods.
      <b>The goal of EcoTrends is to make simplified versions of these datasets, called derived datasets, easily accessible and understandable to a large audience in common formats on a single web site.</b>
    </p>
    <p>
      For example, a raw data set on aboveground net primary production (ANPP) at a grassland site may include data collected from a number of quadrats arrayed along transects within locations that are sampled three times annually for many species. These data can be combined and analyzed to result in one measure of ANPP for that site or location in each year. The EcoTrends web site reports these derived data: one estimate of ANPP for each site or location in each year with the associated metadata PLUS links to the original data, metadata, and the principal investigator who collected the raw data. These annual ANPP estimates can be viewed and downloaded for many sites such that comparisons can be easily made across different grasslands, and with annual estimates from forests, lakes, and marine sites.
      <b>The intent of EcoTrends is to promote synthesis activities and the use of long-term data, not only by scientists, but also more generally by students, teachers, and decision makers.</b>
      </br></br><b>Thus, the EcoTrends website is a portal to:</b>
      <ul>
        <li>a large and diverse collection of standardized long-term ecological datasets</li>
        <li>unique data exploration, download, graphing and synthesis tools</li>
        <li>information about participating research sites and their parent agencies as contextual information to assist in data and trend interpretation</li>
      </ul>
    These datasets, tools, and information are freely available to anyone wishing to explore long-term ecological responses to environmental drivers. Proper credit to both the EcoTrends project and to the original data source need to be provided in any publication or product that uses these data.
    </p>
    <p>
      Although the initial focus of EcoTrends is data collected by sites funded by US agencies, we encourage the addition of datasets from other sites, both in the US and abroad.
      The graphs found in our book, Our Changing World: Insights From Long Term Ecological Research, as well as the data used to generate them, can be easily browsed and viewed here. Browse our site using the menu to the left.
    </p>
    <h3>What EcoTrends is not</h3>
    <p>
      While derived data are necessarily based on and calculated from raw data collected under field and laboratory conditions, it is NOT the intent of EcoTrends to duplicate the rich amount of information found in the raw data. Users interested in the raw data should go to the web link associated with that data. Each derived dataset in EcoTrends has links to the original metadata and/or the URL of the contributor's website that can be accessed from our web page.
    </p>
    <h3>EcoTrends Project Management</h3>
    <p>
      The EcoTrends project started in 2004 as a simple idea between two scientists (D. Peters, A. Lugo) who asked the question: how do we make long-term data easily accessible to a large group of people who may not be familiar with the raw data? A committee of scientists and technical experts from several agencies and sites was formed to insure that different kinds of data (e.g., population, community, ecosystems) from a variety of ecosystems (e.g., lakes, grasslands, marine, polar, alpine) would be well-represented, documented, and made accessible through a common web page. This committee provided the guidance and determination to pull together over 1200 datasets into the EcoTrends project.
    </p>
    <p>
      <b>Committee members: Scientists</b>
    <ul>
      <li>Debra Peters, EcoTrends Project Leader, Jornada Experimental Range (USDA ARS) and Jornada Basin LTER, Las Cruces, NM
      </li>
      <li>Christine Laney, EcoTrends Project Coordinator, Jornada Basin LTER, New Mexico State University, Las Cruces, NM
      </li>
      <li>Scott Collins, Sevilleta LTER, University of New Mexico, Albuquerque, NM</li>
      <li>Charles Driscoll, Hubbard Brook LTER, Syracuse University, Syracuse, NY</li>
      <li>Peter Groffman, Institute of Ecosystem Studies, Millbrook, NY</li>
      <li>Morgan Grove, Baltimore Ecosystem Study (LTER, USDA FS), Baltimore, MD</li>
      <li>Tim Kratz, North Temperate Lakes LTER, University of Wisconsin, Trout Lake, WI
      </li>
      <li>Ariel Lugo, Luquillo Experimental Forest (USDA FS, LTER), San Juan, Puerto Rico
      </li>
      <li>Mark Ohman, California Current Ecosystem LTER, University of San Diego and Scripps Institute of Oceanography, La Jolla, CA</li>
      <li>Bob Waide, LTER Network Office and Luquillo LTER, University of New Mexico, Albuquerque, NM</li>
    </ul>
    </p>
    <p>
      <b>Committee members: Technical experts</b>
    <ul>
      <li>James Brunt, LTER Network Office, University of New Mexico, Albuquerque, NM</li>
      <li>Duane Costa, LTER Network Office, University of New Mexico, Albuquerque, NM</li>
      <li>Don Henshaw, H.J. Andrews Experimental Forest (LTER, USDA FS), Corvallis, OR</li>
      <li>Ken Ramsey, Jornada Basin LTER, New Mexico State University, Las Cruces, NM</li>
      <li>Inigo San Gil, LTER Network Office, University of New Mexico, Albuquerque, NM</li>
      <li>Mark Schildhauer, National Center for Ecological Analysis and Synthesis (NCEAS), University of California at Santa Barbara, Santa Barbara, CA</li>
      <li>Mark Servilla, LTER Network Office, University of New Mexico, Albuquerque, NM</li>
      <li>Wade Sheldon, Georgia Coastal Ecosystem LTER, University of Georgia, Athens, GA</li>
      <li>Marshall White, LTER Network Office, University of New Mexico, Albuquerque, NM</li>
    </ul>
    </p>
    <p>
      <b>Web Application: Developers</b>
    <ul>
      <li>Duane Costa, LTER Network Office, University of New Mexico, Albuquerque, NM</li>
      <li>Mark Servilla, LTER Network Office, University of New Mexico, Albuquerque, NM</li>
    </ul>
    </p>
    <p>
      <b>Collaborators</b></br>
      A large number of scientists and information managers at every site participated by collecting the data, in many cases for many years, making them available to the EcoTrends project, and by checking the quality of the EcoTrends derived data products. Please see individual data set links or site links for more details on the raw data.
    </p>
    <hr>
  </div> <!-- span -->
</div> <!-- row -->
<div class="row">
	<div class="span8">
		<h1>Help Us Grow Our Datasets</h1>
		<h2>We are interested in expanding our database to include additional sites from both within the US and in other countries.</h2>
	</div> <!-- span -->
	<div class="span4">
		<h1>Contact Us</h1>
    <%= form_for @message, url: contact_url do |message_form| %>
        <fieldset>
          <div class="field">
            <%= message_form.text_field :subject, placeholder: "Subject", class:"span4" %>
          </div>

          <div class="field">
            <%= message_form.email_field :email, placeholder: "Email", class:"span4" %>
          </div>

          <div class="field">
            <%= message_form.text_area :content, placeholder: "Message", class:"span4" %>
          </div>
        </fieldset>

        <fieldset>
          <%= recaptcha_tags %>
        </fieldset>

        <fieldset>
          <div class="field" style="padding-top:6px;">
            <%= message_form.submit "Send Message", class: "btn btn-primary" %>
          </div>
        </fieldset>
    <% end %>
	</div> <!-- span -->
</div> <!-- row -->

app/views/home/comparison.erb
<div class="row">
	<div class="span12 backtoresults">
		<a href="#"><%= image_tag "backicon.png", class: "baricon"%>Back to Results</a>
	</div> <!-- span -->
</div> <!-- row -->

<div class="row">
	<div class="span12 comparisonbar">
		<div class="row">
			<div class="span10">
				<h1 style="margin-left: 10px;"class="white">Comparing 3 datasets</h1>
			</div> <!-- span -->
			<div class="span2">
				<a href="#"><%= image_tag "printpagebutton.jpg", style: "float: left; margin-top: 10px; margin-left: -10px;" %></a>
			</div>
		</div> <!-- row -->
	</div> <!-- span -->
</div> <!-- row -->

<div class="row">
	<div class="span12">
		<h1>GRAPH GOES HERE</h1>
	</div> <!-- span -->
</div> <!-- row -->

<div class="row chartrow">
	<div class="span12">
		<div class="row">
			<div class="span4">
				<ul>
					<li>
						<h5>**Matt, I'm skipping this section because part of this functionality may be easier executed by the charting package you choose.</h5>
					</li>
					<li>
						<input type="checkbox"/><h4 class="variable-color">Plant Productivity (Aboveground)</h4><br/>-Jordan Basin / New Mexico
					</li>
				</ul>
			</div> <!-- span -->
		</div> <!-- row -->
	</div> <!-- span -->
</div> <!-- row -->

app/views/home/dataset.erb
<div class="row">
	<div class="span8">
		<div class="tabbable"> <!-- Only required for left/right tabs -->
		  <ul class="nav nav-tabs">
		    <li class="active"><a href="#tab1" data-toggle="tab">OVERVIEW</a></li>
		    <li><a href="#tab2" data-toggle="tab">VIEW TABLE</a></li>
		    <li><a href="#tab3" data-toggle="tab">VIEW CHART</a></li>
		    <div class="dataset-mainaction">
			  <a href="#"><%= image_tag "datastore_off.png" %></a>
			  <a href="#"><%= image_tag "printpagebutton.jpg" %></a>
		  </div>
		  </ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<h1>Plant Productivity (aboveground)</h1>
					<h5>1990 - 2012</h5>
					<h4>EcoTrends Dataset Identifier: ecotrends.9058.1</h4>
					<hr/>
					<div class="twocolumn">
						<h4>Derived Data</h4>
						<p><b>Dataset ID:</b>
						ecotrends.9058.1
						</p>

						<p><b>Site:</b>
						Jornada Basin LTER/Jornada Experimental Range</p>
						<p><b>Station(s):</b>
						Jornada Experimental Range Grassland Plots</p>
						<p><b>Variable:</b>
						aboveground net primary productivity</p>
						<p><b>Unit:</b>
						Gramspermetersquaredperyear</p>
						<p><b>Date Range:</b>
						1990 to 2008</p>
						<p><b>Timescale:</b>
						yearly</p>
						<p><b>Data Version:</b>
						1 of 1</p>
						<p><b>Other Data Versions:</b>
						None</p>

						<p><b>Derived Data</b><br/>
						<a href="#">View data as HTML</a><br/>
						<a href="#">Download as CSV</a></p>

						<h4>Plot:</h4>
						<p><b>Plot Options:</b>
						  Data Points
						  Data Lines
						  Moving Average</p>

						<h4>Source Data</h4>
						<p><b>Principal Investigator(s):</b></p>

						<h4>Organization(s):</h4>
						<p><b>Jornada Basin</b>
						Any use of data or figures from this EcoTrends project dataset must include the following statement(s): "Data and figures were obtained from the EcoTrends Project (http://www.ecotrends.info) funded by the National Science Foundation and USDA Agricultural Research Service. These data are from Jornada Basin (http://jornada-www.nmsu.edu/); ecotrends.9058.1."</p>
					</div>
				</div>
				<div class="tab-pane" id="tab2">
					<p>Howdy, I'm in Section 2.</p>
				</div>
				<div class="tab-pane" id="tab3">
					<p>Howdy, I'm in Section 3.</p>
				</div>
			</div>
		</div>
	</div>
	<div class="span4 dataset-rightside">
			<div class="row">
				<div class="span4">
					<a href="#"><div class="savetofile"></div></a>
					<br/>
				</div> <!-- span -->
			</div> <!-- row -->
			<div class="row">
				<div class="span4">
					<h4><%= image_tag "station.png", class: "icon" %>Research Site</h4>
					<p>Jornada Experimental Range</p>
					<hr/>
					<h4><%= image_tag "globeicon.png", class: "icon" %>Location</h4>
					<p>New Mexico, U.S.A.</p>
					<hr/>
					<h4>Related Publications</h4>
					<p>Peters, D.P.C., Yao, J., Sala, O.E., and Anderson, J. 2012. Directional climate change and potential reversal of desertification in arid and semiarid ecosystems. Global Change Biology 18:151-163. </p>
				</div> <!-- span -->
			</div> <!-- row -->
		</div> <!-- span -->
</div> <!-- row -->

app/views/home/dataset2.erb
<div class="row">
	<div class="span12">
		<div class="tabbable"> <!-- Only required for left/right tabs -->
		  <ul class="nav nav-tabs">
		    <li><a href="#tab1" data-toggle="tab">OVERVIEW</a></li>
		    <li class="active"	><a href="#tab2" data-toggle="tab">VIEW TABLE</a></li>
		    <li><a href="#tab3" data-toggle="tab">VIEW CHART</a></li>
		    <div class="dataset-mainaction">
			  <a href="#"><%= image_tag "datastore_off.png" %></a>
			  <a href="#"><%= image_tag "printpagebutton.jpg" %></a>
		  </div>
		  </ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
					<h1>Plant Productivity (aboveground)</h1>
					<h5>1990 - 2012</h5>
					<table class="table table-striped">
						<thead>
							<tr>
								<td>Year							</td>
								<td>Vegetation				</td>
								<td>Location					</td>
								<td>total NPP (g/m2/y)</td>
								<td>Comments					</td>
							</tr>
						</thead>
						<tr>
							<td>1990															 </td>
							<td>Grassland													 </td>
							<td>BASN															 </td>
							<td>77.2															 </td>
							<td><%= image_tag "stickynote.png" %></td>
						</tr>
						<tr>
							<td>1990															 </td>
							<td>Grassland													 </td>
							<td>BASN															 </td>
							<td>77.2															 </td>
							<td><%= image_tag "stickynote.png" %></td>
						</tr>
						<tr>
							<td>1990															 </td>
							<td>Grassland													 </td>
							<td>BASN															 </td>
							<td>77.2															 </td>
							<td><%= image_tag "stickynote.png" %></td>
						</tr>
						<tr>
							<td>1990															 </td>
							<td>Grassland													 </td>
							<td>BASN															 </td>
							<td>77.2															 </td>
							<td><%= image_tag "stickynote.png" %></td>
						</tr>
						<tr>
							<td>1990															 </td>
							<td>Grassland													 </td>
							<td>BASN															 </td>
							<td>77.2															 </td>
							<td><%= image_tag "stickynote.png" %></td>
						</tr>
						<tr>
							<td>1990															 </td>
							<td>Grassland													 </td>
							<td>BASN															 </td>
							<td>77.2															 </td>
							<td><%= image_tag "stickynote.png" %></td>
						</tr>
						<tr>
							<td>1990															 </td>
							<td>Grassland													 </td>
							<td>BASN															 </td>
							<td>77.2															 </td>
							<td><%= image_tag "stickynote.png" %></td>
						</tr>
						<tr>
							<td>1990															 </td>
							<td>Grassland													 </td>
							<td>BASN															 </td>
							<td>77.2															 </td>
							<td><%= image_tag "stickynote.png" %></td>
						</tr>
					</table>
				</div>
		</div>
	</div>
</div> <!-- row -->

app/views/home/datastore.html.erb
<div class="row">
	<div class="span12 hover">
		<h1>Data Store</h1>
		<h5>Your Saved Datasets</h5>
	</div> <!-- span -->
</div> <!-- row -->
<div class="row">
	<div class="span12 headerbar">
		<button class="btn">Compare Selected</button>
	</div> <!-- span -->
</div> <!-- row -->

<!-- BEGIN SEARCH RESULTS -->
	<div class="row">
		<div class="span12">
			<div class="row">
				<div class="span1">
					<fieldset>
						<form>
							<input type="checkbox"></input>
						</form>
					</fieldset>
				</div> <!-- span -->
				<div class="span9">
					<a href="#"><h4 class="darkbrown">Plant Productivity (aboveground)</h4></a>
					<p class="searchbody">This study measures aboveground biomass by species in 49 1-m2 quadrats at each of 3 grassland locations three times a year to calculate aboveground plant production.</p>
					<p><%= image_tag "station.png", class: "icon" %>
						<a href="#"><b>Jornada Basin</b>/ New Mexico</a>
						 -- NPP Study / Grassland vegetation -- Total grams PerMeterSquaredPerYard</p>
				</div> <!-- span -->
				<div class="span2 searchright">
					<h4>1990 - 2012</h4>
					<a href="#"><%= image_tag "datastore_on.png" %></a>
				</div> <!-- span -->
			</div> <!-- row -->
		</div> <!-- span -->
	</div> <!-- row -->
<hr>

	<div class="row">
		<div class="span12">
			<div class="row">
				<div class="span1">
					<fieldset>
						<form>
							<input type="checkbox"></input>
						</form>
					</fieldset>
				</div> <!-- span -->
				<div class="span9">
					<a href="#"><h4>Plant Productivity (aboveground)</h4></a>
					<p class="searchbody">This study measures aboveground biomass by species in 49 1-m2 quadrats at each of 3 grassland locations three times a year to calculate aboveground plant production.</p>
					<p><%= image_tag "station.png", class: "icon" %>
						<a href="#"><b>Jornada Basin</b>/ New Mexico</a>
						 -- NPP Study / Grassland vegetation -- Total grams PerMeterSquaredPerYard</p>
				</div> <!-- span -->
				<div class="span2 searchright">
					<h4>1990 - 2012</h4>
					<a href="#"><%= image_tag "datastore_on.png" %></a>
				</div> <!-- span -->
			</div> <!-- row -->
		</div> <!-- span -->
	</div> <!-- row -->
<hr>

	<div class="row">
		<div class="span12">
			<div class="row">
				<div class="span1">
					<fieldset>
						<form>
							<input type="checkbox"></input>
						</form>
					</fieldset>
				</div> <!-- span -->
				<div class="span9">
					<a href="#"><h4>Plant Productivity (aboveground)</h4></a>
					<p class="searchbody">This study measures aboveground biomass by species in 49 1-m2 quadrats at each of 3 grassland locations three times a year to calculate aboveground plant production.</p>
					<p><%= image_tag "station.png", class: "icon" %>
						<a href="#"><b>Jornada Basin</b>/ New Mexico</a>
						 -- NPP Study / Grassland vegetation -- Total grams PerMeterSquaredPerYard</p>
				</div> <!-- span -->
				<div class="span2 searchright">
					<h4>1990 - 2012</h4>
					<a href="#"><%= image_tag "datastore_on.png" %></a>
				</div> <!-- span -->
			</div> <!-- row -->
		</div> <!-- span -->
	</div> <!-- row -->
<hr>

	<div class="row">
		<div class="span12">
			<div class="row">
				<div class="span1">
					<fieldset>
						<form>
							<input type="checkbox"></input>
						</form>
					</fieldset>
				</div> <!-- span -->
				<div class="span9">
					<a href="#"><h4>Plant Productivity (aboveground)</h4></a>
					<p class="searchbody">This study measures aboveground biomass by species in 49 1-m2 quadrats at each of 3 grassland locations three times a year to calculate aboveground plant production.</p>
					<p><%= image_tag "station.png", class: "icon" %>
						<a href="#"><b>Jornada Basin</b>/ New Mexico</a>
						 -- NPP Study / Grassland vegetation -- Total grams PerMeterSquaredPerYard</p>
				</div> <!-- span -->
				<div class="span2 searchright">
					<h4>1990 - 2012</h4>
					<a href="#"><%= image_tag "datastore_on.png" %></a>
				</div> <!-- span -->
			</div> <!-- row -->
		</div> <!-- span -->
	</div> <!-- row -->