config/routes.rb
EcoTrends::Application.routes.draw do

  get "comparison" => 'datastores#compare', as: :comparison
  get "testcharts" => 'search#test'
  resources :datastores
  get 'account' => 'accounts#index'
  put 'account/:id' => 'accounts#update'
  get 'login' => 'login#show'
  get 'reset_password' => 'login#edit'
  get 'reset/:token' => "registration#edit"
  put 'reset/:token' => "registration#update"
  post 'login' => 'login#create'
  put 'reset' => 'login#update'
  get 'logout' => 'login#destroy'
  get 'signup' => 'registration#show'
  post 'signup' => 'registration#create'

  get "splash/index"

  get "home/index"

  get "home/about"

  get "home/publications"

  get "home/synthesis"

  get "home/contact"

  get "home/glossary"

  get "home/infographics"

  get "home/datastore"

  get "home/search"

  get "home/test"

  get "home/comparison"

  get "home/dataset"

  get "home/graph"

  get "home/dataset2"

  get "policies" => "home#policies"

  get "participating-sites" => "home#participating"

  post 'contact' => 'contact_us#create'

  get 'contact' =>  'contact_us#new'

  resources :search

  get "metadata" => "search#metadata"
  get "derived-data/:id" => "search#data"

  root :to => 'splash#index'

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_filter :allow_only_signed_in
  def index
    @dataset_count ||= ExtracatMetadata.count
    @site_count ||= ExtracatMetadata.sites.count
  end
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/splash/_footer.html.erb
				<div class="footbox">
		      <ul>
		      	<a href="/policies"><li>Policies & Guidelines |&nbsp</li></a>
		      	<a href="/home/contact"><li>Contact Us |&nbsp</li></a>
		      	<a href="/home/glossary"><li>Glossary</li></a>
		      </ul>

					<div style="text-align: center; margin-top:20px;">
	          <a href="http://www.fs.fed.us/" target="_blank">
		    <%= image_tag 'FS.gif', width: "34", height: "36", border: "0"%>
	            </a>
	            <a href="http://www.ars.usda.gov" target="_blank">
		    <%= image_tag 'ARS2.gif', width: "36", height: "36", border: "0"%>
	            </a>
	            <a href="http://www.nceas.ucsb.edu" target="_blank">
		    <%= image_tag 'NCEAS.gif', width: "36", height: "36", border: "0"%>
	            </a>
	            <a href="http://www.lternet.edu/" target="_blank">
		    <%= image_tag 'LTER_small.gif', width: "30", height: "36", border: "0"%>
	            </a> <a href="http://www.nsf.gov/" target="_blank">
		    <%= image_tag 'NSF.gif', width: "36", height: "36", border: "0"%>
	            </a>
	            <a href="http://www.USGS.gov/" target="_blank">
		    <%= image_tag 'USGS.gif', width: "45", height: "36", border: "0"%>
	            </a>
	            <a href="http://www.nmsu.edu/" target="_blank">
		    <%= image_tag 'nmsu.gif', width: "33", height: "36", border: "0"%>
	            </a>
	            <a href="http://www.energy.gov/" target="_blank">
		    <%= image_tag 'doe.gif', width: "36", height: "36", border: "0"%>
	            </a>
	            <a href="http://www.esa.org/" target="_blank">
		    <%= image_tag 'esa.png', width: "40", height: "68", border: "0"%>
	            </a>
	        </div>
		<p><strong>Disclaimer and Legal Statement:</strong> This material is based upon work supported by
	           the National Science Foundation under Grant number DEB-0080412. Any opinions,
	           findings, conclusions, or recommendations expressed in the material are those
	           of the author(s) and do not necessarily reflect the views of the National
	           Science Foundation or New Mexico State University.
	        </p>
			      <p>All Rights Reserved. EcoTrends &copy; <%= DateTime.now.year%>.</p>
				</div>

app/views/splash/index.html.erb
<div style="margin-bottom: 60px;" class="row home-copy">
          <div class="span7">
            <h1>Ecological Data on Demand</h1>
            <h5>The EcoTrends Project is designed to promote and enable the use and synthesis of long-term data to examine trends in the Earth's ecosystems.</h5>
            <p>
              Welcome to EcoTrends. We are currently verifying the data on this website with the contributing researchers; please read the <b>disclaimer</b> below.
              The Earth's environment is changing at local, regional, and global scales. Dramatic changes have occurred over the past century in climate, land cover, and habitat availability with important consequences for plant, animal, microbial, and human populations. Long-term data provide the only means to assess the rate and direction of change, to distinguish directional trends from short-term variability, and to forecast environmental conditions in the future.
              The EcoTrends Project is designed to promote and enable the use and synthesis of long-term data to examine these trends in the Earth's ecosystems.
              The EcoTrends project is a collaborative effort among state and federal agencies and institutions, at present primarily in the US, to make long-term ecological data easy to access, analyze, and compare within and across sites. This website is a portal to:
              <ul>
                <li>
                  a large and diverse collection of standardized long-term ecological datasets and their metadata (> 1200 datasets)

                </li>
                <li>
                  unique data exploration, download, graphing and synthesis tools
                </li>
                <li>
                  information about participating research sites and their parent agencies
                </li>
              </ul>
              These datasets, tools, and information are available to anyone who would like to: view trends in ecological variables for one or multiple sites or pursue additional statistical analyses of within-site and cross-site comparisons. Please read our <a href="/policies">data use and citation policies</a> before downloading data.
              We are interested in expanding our database to include additional sites from both within the US and in other countries.<a href="/home/about">Please contact us</a> for details.
              Any use of data or figures from the EcoTrends project must:
            <ul>
              <li>
                Include the following statement (replace [Original Data Source] and [EcoTrends Dataset Identifier] with values from the website as appropriate):              </li>
              <li>
                "Data and figures were obtained from the <a href="/">EcoTrends Project</a> funded by the National Science Foundation and USDA Agricultural Research Service. These data are from [Original Data Source]; [EcoTrends Dataset Identifier]."
              </li>
              <li>
                Submit a pdf of the final publication using EcoTrends data to: ecotrend@nmsu.edu
              </li>
            </ul>
            </p>
          </div> <!-- span -->
          <div class="span5">
          	<div class="row">
          		<div class="span1">
          			<%= image_tag "large-datastore.png" %>
          		</div> <!-- span -->
          		<div class="span4">
								<h1><%= link_to "My Data Store", datastores_path%></h1>
								<p>Save Datasets for easy retrieval later. Compare, chart or just download them for your research. </p>
          		</div> <!-- span -->
          	</div> <!-- row -->
          	<div class="row">
          		<div class="span1">
          			<%= image_tag "large-charting.png" %>
          		</div> <!-- span -->
          		<div class="span4">
								<h1><%= link_to "Powerful Charting", '/datastores/#charting'%></h1>
								<p>Build charts to visualize values within our data sets. </p>
          		</div> <!-- span -->
          	</div> <!-- row -->
          	<div class="row">
          		<div class="span1">
          			<%= image_tag "large-glossary.png" %>
          		</div> <!-- span -->
          		<div class="span4">
								<h1><%= link_to "Glossary", home_glossary_path%></h1>
								<p>Use our Glossary to stay informed on terminology.</p>
          		</div> <!-- span -->
          	</div> <!-- row -->
            <div class="row"><!-- row -->
              <div class="span1">
                <%= image_tag "publications_icon.png" %>
              </div> <!-- span -->
              <div class="span4">
                <h1><%= link_to "Publications", home_publications_path%></h1>
                <p>Submit a pdf of any final publication using EcoTrends data.</p>
              </div> <!-- span -->
            </div> <!-- row -->

            <div class="row">
              <div class="span1">
                <%= image_tag "search-icon.png" %>
              </div> <!-- span -->
              <div class="span4">
                <h1><%= link_to "Search", "/search"%></h1>
                <p>Search thousands of datasets. </p>
              </div> <!-- span -->
            </div>
             <!-- row -->
            <div class="row">
              <div class="span1" >
                <h2 class="splashheader" style="font-size: 3em; padding-left:10px;"><i class="fa fa-building-o" style="color: #5f98ce;"></i><h2>
              </div> <!-- span -->
              <div class="span4">
                <h1><%= link_to "Participating Sites", "/participating-sites"%></h1>
              </div> <!-- span -->
            </div> <!-- row -->
          </div> <!-- span -->
        </div><!--/row-->